import type { Category } from '@/types'

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'transportation',       name: 'Transportation',        icon: 'Car',             isCustom: false, type: 'expense' },
  { id: 'food-groceries',       name: 'Food & Groceries',      icon: 'ShoppingCart',    isCustom: false, type: 'expense' },
  { id: 'health',               name: 'Health',                icon: 'Heart',           isCustom: false, type: 'expense' },
  { id: 'housing',              name: 'Housing',               icon: 'Home',            isCustom: false, type: 'expense' },
  { id: 'fuel-gas',             name: 'Fuel / Gas',            icon: 'Fuel',            isCustom: false, type: 'expense' },
  { id: 'restaurants',          name: 'Restaurants',           icon: 'UtensilsCrossed', isCustom: false, type: 'expense' },
  { id: 'medical-pharmacy',     name: 'Medical / Pharmacy',    icon: 'Pill',            isCustom: false, type: 'expense' },
  { id: 'rent-mortgage',        name: 'Rent / Mortgage',       icon: 'Building',        isCustom: false, type: 'expense' },
  { id: 'vehicle-maintenance',  name: 'Vehicle Maintenance',   icon: 'Wrench',          isCustom: false, type: 'expense' },
  { id: 'supermarket',          name: 'Supermarket',           icon: 'Store',           isCustom: false, type: 'expense' },
  { id: 'health-insurance',     name: 'Health Insurance',      icon: 'Shield',          isCustom: false, type: 'expense' },
  { id: 'utilities',            name: 'Utilities',             icon: 'Zap',             isCustom: false, type: 'expense' },
  { id: 'entertainment',        name: 'Entertainment',         icon: 'Tv',              isCustom: false, type: 'expense' },
  { id: 'education',            name: 'Education',             icon: 'GraduationCap',   isCustom: false, type: 'expense' },
  { id: 'investments-savings',  name: 'Investments / Savings', icon: 'TrendingUp',      isCustom: false, type: 'any' },
  { id: 'salary',               name: 'Salary',                icon: 'Banknote',        isCustom: false, type: 'income' },
  { id: 'freelance',            name: 'Freelance',             icon: 'Laptop',          isCustom: false, type: 'income' },
  { id: 'interest',             name: 'Interest',              icon: 'Percent',         isCustom: false, type: 'income' },
  { id: 'rental-income',        name: 'Rental income',         icon: 'KeyRound',        isCustom: false, type: 'income' },
  { id: 'refund',               name: 'Refund',                icon: 'RotateCcw',       isCustom: false, type: 'income' },
  { id: 'other',                name: 'Other',                 icon: 'MoreHorizontal',  isCustom: false, type: 'any' },
]
