import {
  Car, ShoppingCart, Heart, Home, Fuel, UtensilsCrossed, Pill, Building,
  Wrench, Store, Shield, Zap, Tv, GraduationCap, TrendingUp, MoreHorizontal,
  Wallet, Coffee, Plane, Shirt, Dumbbell, Music, Gift, Bus, Bike, Baby,
  PawPrint, Camera, Smartphone, Wifi, BookOpen, Briefcase, DollarSign,
  CreditCard, Landmark, ShoppingBag, Scissors, Hammer, Paintbrush, Leaf,
  Sun, Moon, Star, Package, Truck, Headphones, Monitor, Gamepad2, Flower,
  Banknote, Laptop, Percent, KeyRound, RotateCcw,
} from 'lucide-react'

import type { LucideIcon } from 'lucide-react'

/** All icons available for category selection. Add entries here to expand the picker. */
export const ICON_MAP: Record<string, LucideIcon> = {
  Car,
  ShoppingCart,
  Heart,
  Home,
  Fuel,
  UtensilsCrossed,
  Pill,
  Building,
  Wrench,
  Store,
  Shield,
  Zap,
  Tv,
  GraduationCap,
  TrendingUp,
  MoreHorizontal,
  Wallet,
  Coffee,
  Plane,
  Shirt,
  Dumbbell,
  Music,
  Gift,
  Bus,
  Bike,
  Baby,
  PawPrint,
  Camera,
  Smartphone,
  Wifi,
  BookOpen,
  Briefcase,
  DollarSign,
  CreditCard,
  Landmark,
  ShoppingBag,
  Scissors,
  Hammer,
  Paintbrush,
  Leaf,
  Sun,
  Moon,
  Star,
  Package,
  Truck,
  Headphones,
  Monitor,
  Gamepad2,
  Flower,
  Banknote,
  Laptop,
  Percent,
  KeyRound,
  RotateCcw,
}
