import {
  Car, ShoppingCart, Heart, Home, Fuel, UtensilsCrossed, Pill, Building,
  Wrench, Store, Shield, Zap, Tv, GraduationCap, TrendingUp, MoreHorizontal,
  Wallet, Coffee, Plane, Shirt, Dumbbell, Music, Gift, Bus, Bike, Baby,
  PawPrint, Camera, Smartphone, Wifi, BookOpen, Briefcase, DollarSign,
  CreditCard, Landmark, ShoppingBag, Scissors, Hammer, Paintbrush, Leaf,
  Sun, Moon, Star, Package, Truck, Headphones, Monitor, Gamepad2, Flower,
  Banknote, Laptop, Percent, KeyRound, RotateCcw,
  // — additional icons —
  Receipt, PiggyBank, Coins, ArrowRightLeft, TrendingDown, BarChart2,
  Wine, Beer, Pizza, Apple, Salad, IceCream2,
  Stethoscope, Hospital, Activity, Syringe,
  Train, Ship, Navigation, MapPin, Globe, Map,
  Sofa, Lamp, Thermometer, Droplets, BedDouble, Bath,
  Factory, ClipboardList, FileText, FolderOpen, Users, UserCheck,
  Clapperboard, Ticket, Popcorn,
  Tag, QrCode, Barcode,
  Flame, Snowflake, Umbrella, Lock, Clock, Utensils,
  Trees, Mountain, Waves, Watch,
} from 'lucide-react'

import type { LucideIcon } from 'lucide-react'

/** All icons available for category selection. Add entries here to expand the picker. */
export const ICON_MAP: Record<string, LucideIcon> = {
  // — transport —
  Car,
  Bus,
  Bike,
  Truck,
  Plane,
  Train,
  Ship,
  Fuel,
  Navigation,
  MapPin,
  // — food & drink —
  UtensilsCrossed,
  Utensils,
  Coffee,
  Pizza,
  Wine,
  Beer,
  Apple,
  Salad,
  IceCream2,
  // — shopping —
  ShoppingCart,
  ShoppingBag,
  Store,
  Tag,
  Barcode,
  QrCode,
  Scissors,
  // — finance —
  Wallet,
  Banknote,
  DollarSign,
  CreditCard,
  Landmark,
  PiggyBank,
  Coins,
  Receipt,
  Percent,
  ArrowRightLeft,
  TrendingUp,
  TrendingDown,
  BarChart2,
  // — health —
  Heart,
  Pill,
  Stethoscope,
  Hospital,
  Activity,
  Syringe,
  Dumbbell,
  // — home —
  Home,
  Building,
  Sofa,
  Lamp,
  Thermometer,
  Droplets,
  BedDouble,
  Bath,
  Hammer,
  Paintbrush,
  Wrench,
  // — utilities & tech —
  Zap,
  Wifi,
  Smartphone,
  Laptop,
  Monitor,
  Tv,
  Headphones,
  Camera,
  // — people & family —
  Baby,
  PawPrint,
  Users,
  UserCheck,
  // — education & work —
  GraduationCap,
  BookOpen,
  Briefcase,
  ClipboardList,
  FileText,
  FolderOpen,
  Factory,
  // — entertainment —
  Music,
  Gamepad2,
  Clapperboard,
  Ticket,
  Popcorn,
  // — travel & outdoors —
  Globe,
  Map,
  Trees,
  Mountain,
  Waves,
  Leaf,
  Flower,
  Sun,
  Moon,
  Snowflake,
  Flame,
  Umbrella,
  // — misc —
  Gift,
  Package,
  Shirt,
  Watch,
  Star,
  Shield,
  Lock,
  KeyRound,
  Clock,
  RotateCcw,
  MoreHorizontal,
}
