import { v4 as uuid } from 'uuid'
import { db } from '@/db'
import type { Transaction } from '@/types'

const RETENTION_AGE_YEARS = 5

function getYearBounds(year: number): { from: string; to: string } {
  return {
    from: `${year}-01-01T00:00:00.000Z`,
    to: `${year}-12-31T23:59:59.999Z`,
  }
}

async function getVehicleLinkedTransactionIds(): Promise<Set<string>> {
  const [fuelLogs, services] = await Promise.all([
    db.fuelLogs.toArray(),
    db.vehicleServices.toArray(),
  ])

  const ids = new Set<string>()
  for (const log of fuelLogs) {
    if (log.transactionId) ids.add(log.transactionId)
  }
  for (const service of services) {
    if (service.transactionId) ids.add(service.transactionId)
  }

  return ids
}

export async function getCompactableTransactionsForYear(year: number): Promise<Transaction[]> {
  const { from, to } = getYearBounds(year)
  const [yearTxs, vehicleLinkedIds] = await Promise.all([
    db.transactions.where('date').between(from, to, true, true).toArray(),
    getVehicleLinkedTransactionIds(),
  ])

  return yearTxs.filter((tx) => !vehicleLinkedIds.has(tx.id))
}

export async function getCompactableTransactionYears(): Promise<number[]> {
  const allTransactions = await db.transactions.toArray()
  const vehicleLinkedIds = await getVehicleLinkedTransactionIds()
  const minYear = new Date().getUTCFullYear() - RETENTION_AGE_YEARS

  const years = new Set<number>()
  for (const tx of allTransactions) {
    if (vehicleLinkedIds.has(tx.id)) continue
    const year = new Date(tx.date).getUTCFullYear()
    if (!Number.isFinite(year)) continue
    if (year <= minYear) years.add(year)
  }

  return Array.from(years).sort((a, b) => a - b)
}

type CompactBucket = {
  type: 'income' | 'expense'
  amount: number
  accountId: string
  categoryId: string
  currency: string
}

export async function compactTransactionsYear(year: number): Promise<{
  compactedCount: number
  generatedCount: number
}> {
  const sourceTransactions = await getCompactableTransactionsForYear(year)
  if (sourceTransactions.length === 0) {
    return { compactedCount: 0, generatedCount: 0 }
  }

  const bucketMap = new Map<string, CompactBucket>()

  const addBucket = (
    type: 'income' | 'expense',
    amount: number,
    accountId: string,
    categoryId: string,
    currency: string,
  ) => {
    if (amount <= 0) return
    const key = `${type}::${accountId}::${categoryId}::${currency}`
    const existing = bucketMap.get(key)
    if (existing) {
      existing.amount += amount
      return
    }
    bucketMap.set(key, { type, amount, accountId, categoryId, currency })
  }

  for (const tx of sourceTransactions) {
    const categoryId = tx.categoryId || 'other'

    if (tx.type === 'income') {
      addBucket('income', tx.amount, tx.accountId, categoryId, tx.currency)
      continue
    }

    if (tx.type === 'expense') {
      addBucket('expense', tx.amount, tx.accountId, categoryId, tx.currency)
      continue
    }

    addBucket('expense', tx.amount, tx.accountId, categoryId, tx.currency)
    if (tx.toAccountId) {
      addBucket('income', tx.amount, tx.toAccountId, categoryId, tx.currency)
    }
  }

  const compactedAt = new Date().toISOString()
  const compactedDate = `${year}-12-31T23:59:59.999Z`

  const generatedTransactions: Transaction[] = Array.from(bucketMap.values()).map((bucket) => ({
    id: uuid(),
    type: bucket.type,
    amount: Math.round(bucket.amount),
    date: compactedDate,
    categoryId: bucket.categoryId,
    accountId: bucket.accountId,
    description: `Compacted ${year} summary`,
    notes: `Generated by yearly compaction at ${compactedAt}`,
    status: 'cleared',
    currency: bucket.currency,
    labels: ['compacted'],
  }))

  await db.transaction('rw', db.transactions, async () => {
    await db.transactions.bulkDelete(sourceTransactions.map((tx) => tx.id))
    if (generatedTransactions.length > 0) {
      await db.transactions.bulkAdd(generatedTransactions)
    }
  })

  return {
    compactedCount: sourceTransactions.length,
    generatedCount: generatedTransactions.length,
  }
}
